c_compiler:    # [win]
  - vs2017     # [win]
  - vs2017     # [win]
cxx_compiler:  # [win]
  - vs2017     # [win]
  - vs2017     # [win]
vc:            # [win]
  - 14.1       # [win]
  - 14.1       # [win]
python:        # [win]
  - 3.6        # [win]
  - 3.7        # [win]

c_compiler:    # [osx]
  - llvm       # [osx]
  - clang      # [osx]
cxx_compiler:  # [osx]
  - llvm       # [osx]
  - clangxx    # [osx]
llvm:          # [osx]
  - 4.0        # [osx]
