{% set version = "2.0" %}

package:
  name: reaktoro
  version: {{ version }}

source:
  # url: https://github.com/reaktoro/reaktoro/archive/v{{ version }}.tar.gz
  # sha256: e682f2846d5de9fa6ee9565e54762653a1c3ecb46e7932a46e1d4881b8b64cc4

#  Use the config below to use an archive from a branch to test conda-forge builds without creating GitHub releases
  # url: https://github.com/allanleal/reaktoro/archive/{branch-name-here}.tar.gz
  # sha256: 6f8eb83086f53d89f2144380728e1403fd6b45b903a673c6a086b3523170cf4a
  git_url: https://github.com/allanleal/reaktoro.git
  git_rev: v2.0-preview
  # git_depth: 1

build:
  number: 3
  # skip: true  # [py2k or c_compiler == 'toolchain_c' or py < 39 or (win and vc<15)]
  skip: true  # [py < 39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - catch2
    - ccache   # [unix]
    - clcache  # [win]
  host:
    - python
    - numpy
    - pip
    - pandas
    - setuptools
    - wheel
    - tabulate
    - pybind11
    - pugixml
    - thermofun 0.3.7
    - nlohmann_json >=3.6.1
  run:
    - python
    - numpy x.x
  run_constrained:                                            # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - reaktoro

about:
  home: https://github.com/reaktoro/reaktoro
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: A unified framework for modeling chemically reactive systems
  description: |
    Reaktoro is a unified framework for modeling chemically reactive systems.
    It provides methods for chemical equilibrium and kinetic calculations
    for multiphase systems. Reaktoro is mainly developed in C++ for
    performance reasons. A Python interface is available for a more
    convenient and simpler use.
  doc_url: https://reaktoro.org
  dev_url: https://github.com/reaktoro/reaktoro

extra:
  recipe-maintainers:
    - allanleal
    - tadeu
    - nicoddemus
